#!/bin/bash

if [ -n "$MAVEN_MIRROR" ]; then
  mkdir -p $HOME/.m2
  cat <<EOF >$HOME/.m2/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <mirrors>
    <mirror>
      <mirrorOf>*</mirrorOf>
      <url>$MAVEN_MIRROR</url>
      <id>mirror</id>
    </mirror>
  </mirrors>
</settings>
EOF
fi

exec $(dirname "$0")/_assemble "$*"
